---
title: "R Notebook"
output: html_notebook
---



```{r}
library(serial)
library(tidyverse)
```

```{r}
filename = "clarityexport.csv" # Clarity Export file
clarity_dat = read_csv(filename)

hourgluc = clarity_dat %>% 
  mutate(
    `Timestamp (YYYY-MM-DDThh:mm:ss)`= lubridate::parse_date_time(
      `Timestamp (YYYY-MM-DDThh:mm:ss)`, 
      c("YmdHMS", "mdY"))
    ) %>% 
  group_by(hour=  lubridate::floor_date(`Timestamp (YYYY-MM-DDThh:mm:ss)`, "hour")) %>% 
  summarise(glucose=mean(`Glucose Value (mg/dL)`,na.rm = T)) %>% 
  arrange((hour)) %>% 
  mutate(
    category = case_when(
      glucose < 150 ~ 1,
      glucose < 300 ~ 2,
      TRUE ~  3
    )
  )

# Print collapsed data from designated range
hourgluc %>% 
  filter(hour<as.POSIXct("2018-01-02") & hour>=as.POSIXct("2018-01-01")) %>% 
  pull(glucose) %>% 
  round(digits=3) %>%  
  paste(collapse = ", ")
```


```{r}
val = intToUtf8(as.integer( hourgluc$category[1:30])) # Covert data into bytes to send over serial port

acon = serialConnection( name = "comArd",port = "cu.usbmodem1411",mode = "9600,n,8,1") # Fill in with appropriate port parameters
. 
open(acon) # Initialize Connection to port

# Send data to port
serial::write.serialConnection(con = acon,
                               dat = (val) 
                               )

## Read data from port (for debugging purposes
# serial::read.serialConnection(acon)

close(acon)
```

